In [302]:
import numpy as np 
import matplotlib

In [303]:
#fully connected neural network, every neuron has a unique connection to every neuron 
#building a neuron 
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [2, 1.8, -0.8, 1.2],
           [5, 0.2, -2.5, .6]]
biases = [2, 3, 0.5]
output = np.dot(weights, input) + bias


ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:
# xip combines two lists in to a list of list, creates a lits by pairing the 0th element of different lists 
 
layer_outputs = [] 


#lol of weight and biases pair
for neuron_weights, neuron_bias in zip(weights, biases): #takes pairs of neuron weights and neuron biases 
    neuron_output = 0 
    
    for n_input, weight in zip(inputs, neuron_weights): 
        neuron_output += n_input*weight
        
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

#The shape of array: l = [1,5,6,2] is (4,). 1D array, vector 

lol = [[1, 5, 6, 2]   #the shape here is (2,4)
       [3, 2, 1, 3]] #2d Array,  matrix  

In [ ]:
#a tensor is an objetc that can be represented as an array 
inputs = [[1, 2, 3, 2.5], 
          [2, 5, -1, 2], 
          [-1.5, 2.7, 3.3, -0.8]]  
weights = [[0.2, 0.8, -0.5, 1],
           [2, 1.8, -0.8, 1.2],
           [5, 0.2, -2.5, .6]]
biases = [2, 3, 0.5]
output = np.dot(weights, inputs) + bias #weights has to be first, indexes accordingly 
print(output)

In [ ]:
#modelling two layers of neurons, move towards object oreinted programming 
#batches help with generalization
#normal batch sizes are 32/64
#hidden layers are called hidden layers, as we do not define or decide how the layer changes in values
output = np.dot(inputs, np.array(weights).T) + biases
print(output)
 



In [ ]:
np.random.seed(0)#initialize the random number generator

X = [[1, 2, 3, 2.5], 
     [2, 5, -1, 2], 
     [-1.5, 2.7, 3.3, -0.8]]


class Layer_Dense: 
    #n_neurons: number of neurons ,n_inputs: number of features. 
    def __init__(self, n_features , n_neurons): 
        self.weights = np.random.randn(n_features, n_neurons) #shape is opposite of what was done earlier
        
        #do so like this as don't need to do transpose later
        
        self.biases = np.zeros((1, n_neurons)) #(1,n_neurons) is the first parameters not two different parameters 
        
    def forward(self, inputs): 
        self.output = np.dot(inputs, self.weights) + self.biases #output from previous layer  

 


#size of the inputs: How many features for each sample
layer1 = Layer_Dense(4, 3) #Output from layer 1 is input 2 layer 2 
layer2 = Layer_Dense(3, 6) 

layer1.forward(X) 
# print(layer1.output)
layer2.forward(layer1.output) 
print(layer2.output)

In [ ]:
#step function:  
#Every neuron in the hidden layer as well as the output layer is going to have an activation function associated
#geneally, the output layer is going to have a different activation function than what is used in the hidden layers
# using sigmoid activation function is easier and more reliabel to train a neural network due to the granularity of the output
#ReLu: rectified linear activvation function __/ curve 
#sigmoid has an issue refered to as the vanishing gradient function 


inputs = [0,2, -1, 3,.3, -2.7, 1.1, 2.2, -100]
output  = []

for i in inputs: 
    if i > 0: 
        output.append(1)
    else: 
        output.append(0)
#Writing a class for the ReLU activation function 

class Activation_ReLU: 
    def forward(self, inputs): 
        self.output = np.maximum(0, inputs) 
    

    


In [ ]:
import nnfs

In [ ]:
def create_data(points, classes):  # how many feature sets over howevery many classes, and two features in side the feature sets (x and y) 
   #X: denotes feature sets, y: denotes targets or the classifications  
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype = 'uint8')#8 bit integer

    #function that will generate a random dataset for us 
    for class_number in range(classes): 
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0,1, points) 
        t = np.linspace(class_number*4, (class_number+1)*4, points)+ np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number 
    return X, y 
    
import matplotlib.pyplot as plt

X, y =create_data(100,3)
print(y)
plt.scatter(X[:, 0], X[:,1], c=y, s= 40, cmap= plt.cm.Spectral) 
plt.show()

In [431]:
#Attempt to use the data from above for a classification problem

np.random.seed(0)#initialize the random number generator

class Layer_Dense: 
    #n_neurons: number of neurons ,n_inputs: number of features. 
    def __init__(self, n_features , n_neurons): 
        self.weights = np.random.randn(n_features, n_neurons) #shape is opposite of what was done earlier
        
        #do so like this as don't need to do transpose later
        
        self.biases = np.zeros((1, n_neurons)) 
        #(1,n_neurons) is the first parameters not two different parameters 
        
    def forward(self, inputs): 
        self.output = np.dot(inputs, self.weights) + self.biases #output from previous layer  

class Activation_ReLU: 
    def forward(self, inputs): 
        self.output = np.maximum(0, inputs) 

class Activation_Softmax:
    def forward(self, inputs): 
        exp_values =np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
        probabilities = exp_values/ np.sum(exp_values,axis =1, keepdims = True) 
        self.output = probabilities 

class Loss: 
    #ouptut: output from the model, y: intended output values
    def calculate(self, output, y): 
        sample_losses = self.forward(ouput, y) 
        data_loss = np.mean(sample_losses) 
        return data_loss
        
class Loss_CatergoricalCrossentropy(Loss): 
    def forward(self, y_pred, y_true): 
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, np.exp(-7), 1- np.exp(-7)) 
        #taking into account one-hot encoded targets and sparse targets
        if len(y_true.shape) ==1: 
            correct_confidences = y_pred_clipped[range(samples), y_true] 
        elif len(y_true.shape) == 2 : 
            correct_confidences = np.sum (y_pred* y_true, axis =1) 
        negative_log_likehlihoods = -log(correct_confidents) 
        return negative_log_likelihoods  
class Accuracy: 
    def Results(self, predictions, class_targets): 
        self.results = np.mean(np.array(predictions)  ==np.array(class_targets))
        return self.results
    

In [ ]:
#size of the inputs: How many features for each sample

#(2 features, 100 data points) 
layer1 = Layer_Dense(2, 100)  

# take input from the layer and creates a relu for the entrire layer
activation1= Activation_ReLU()

layer1.forward(X)

activation1.forward(layer1.output)


# softamx actiavtion function is specifically used for the output layer on the classification style neural network problem 
#Relu us not helpful for the output layer as it always clips all negative numbers as 0, regardless of the magnitude (so impossible to classify if all the nunmbers are negative)


#The combination of exponentiation and normalization is called the softmax function

layer_outputs = [[4.8, 1.21, 2.385], 
                 [8.9, -1.81, 0.2],
                 [1.41, 1.051, 0.026]]

exp_values = np.exp(layer_outputs)
norm_values = exp_values/np.sum(exp_values,axis = 1, keepdims= True) 
#need to set the axis to 1 for row addidition and keepdims to true to make sure the normalization is row-wise 


In [ ]:
X, y = create_data(100, 3)  

dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()


dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

In [370]:
#our classification model doesn't output classifcication, it outputs probability distrubition 
# the general choice of loss function for classification problems using softmax as the activation function 
#for the output layer is categorical cross-entropy

#one-hot encoding: A vector that is n classes long, filled with zeros expect at the index with target class (which would be 1)
# When we calculate categorical cross-entropy with one hot vectors, it allows us to simplify it to -log(predicted target class)

softmax_outputs= np.array([[0.7, 0.1, 0.2], 
                   [0.1, 0.5, 0.4], 
                   [0.02, 0.9, 0.08]])
class_targets = [0, 1, 1]

for targ_idx, distribution in zip(class_targets, softmax_outputs): 
    print(distribution[targ_idx])

# or 
y1 = softmax_outputs[[0,1,2], class_targets]
print(y1) 

#or 
y2 = softmax_outputs[range(len(softmax_outputs)), class_targets]
print(y2)

# now, we find the categotrial cross-entropoy loss 

loss=(-np.log(y2))
print(loss)

average_loss = np.mean(loss)
print(average_loss)

# here, we need to clip the values, to avoid results such as -log(0). We do so in the following way

y_clipped= np.clip(y2, np.exp(-7), 1- np.exp(-7))


0.7
0.5
0.9
[0.7 0.5 0.9]
[0.7 0.5 0.9]
[0.35667494 0.69314718 0.10536052]
0.38506088005216804


In [ ]:
loss_function = Loss_CategoricalCrossentropy()
loss = loss_function.calculate()


In [435]:
softmax_outputs= np.array([[0.7, 0.1, 0.2], 
                   [0.1, 0.5, 0.4], 
                   [0.02, 0.9, 0.08]])
predictions = np.argmax(softmax_outputs, axis =1) 
print(predictions) 
class_targets = [1, 1, 1]
print(np.mean(np.array([1, 1, 1]) == np.array([0, 0, 1])) )

accuracy = Accuracy() 
print(accuracy.Results(predictions, class_targets)) 



[0 1 1]
0.3333333333333333
0.6666666666666666
